@HostAddress = https://localhost:7011

###
# Get Weather Forecast for Redmond, WA (98052)
GET {{HostAddress}}/api/WeatherForecast?api-version=2023-06-06
Accept: application/json

###
# Get Weather Forecast for specific zip code (Dallas, TX - 75014)
GET {{HostAddress}}/api/WeatherForecast/75014?api-version=2023-06-06
Accept: application/json

###
# Get Weather Forecast for Redmond, WA
GET {{HostAddress}}/api/WeatherForecast/98052?api-version=2023-06-06
Accept: application/json

###
# Get Weather Forecast for invalid zip code (404 Not Found)
GET {{HostAddress}}/api/WeatherForecast/00000?api-version=2023-06-06
Accept: application/json

###
# Test error handling middleware
GET {{HostAddress}}/api/WeatherForecast/Throw?api-version=2023-06-06
Accept: application/json

###
# Register a new user
POST {{HostAddress}}/api/Users?api-version=2023-06-06
Content-Type: application/json

{
  "firstName": "Xavier",
  "lastName": "John",
  "email": "xavier@heaven.com",
  "password": "Super!Complex6"
}

###
# Get greeting for user
GET {{HostAddress}}/api/Users/xavier?api-version=2023-06-06
Accept: application/json

###
# Bad Request - invalid email
POST {{HostAddress}}/api/Users?api-version=2023-06-06
Content-Type: application/json

{
  "firstName": "Xavier",
  "lastName": "John",
  "email": "xavier",
  "password": "Super!Complex6"
}

###
# Bad Request - weak password
POST {{HostAddress}}/api/Users?api-version=2023-06-06
Content-Type: application/json

{
  "firstName": "Xavier",
  "lastName": "John",
  "email": "xavier@heaven.com",
  "password": "SimplePassword"
}

###
# Bad Request - multiple validation errors
POST {{HostAddress}}/api/Users?api-version=2023-06-06
Content-Type: application/json

{
  "firstName": "",
  "lastName": "",
  "email": "xavier",
  "password": "Super!Complex6"
}

````````


# Response